### PR TITLE
fix: allow to see multiple xblock mindmap in lms

### PR DESCRIPTION
**Pull request by johnvente**
**Description**
When we create more than one XBlock per unit  in the LMS, it breaks due to a draggable plugin from jsmind that was initialized previously, which is weird because each XBlock in the LMS is an iframe. This fix allows us to create any number of XBlocks  without that issue

BEFORE           | NOW
:-------------------------:|:-------------------------:
  |  

### How to test 

1. Once you have the XBlock in your environment, go to Studio > create a unit > create some XBlock-type mind maps.
2. Publish the changes.
3. Go to the LMS to see the unit.

**Merge checklist:**
Check off if complete *or* not applicable:
- [X] Version bumped
- [X] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Fixup commits are squashed away
- [ ] Unit tests added/updated
- [ ] Manual testing instructions provided
- [ ] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

### CODE REVIEW

**Review by Ian2012 — APPROVED** [review]

**Review by mariajgrimaldi — APPROVED** [review]
The error was fixed! Thanks

**Comment by johnvente** [comment]
> @johnvente, when I add more than one block to the unit it does not allow me to display the instructions for use, it closes by itself.

Nice catch! I've done the fix for that

**Comment by BryanttV** [comment]
Good! It no longer closes by itself, however, when I open/close one block's instructions, the other blocks do the same.

**Comment by johnvente** [comment]
> @johnvente, good! It no longer closes by itself, however, when I open/close one block's instructions, the other blocks do the same.

@BryanttV too odd, fixed it! 🚀

**Review by BryanttV — APPROVED** [review]

**Pull request merged**
